// X.Org Documentation Data Model
// Base URL for all documentation links
const BASE_URL = 'https://www.x.org/releases/current/doc/';

const DOCS_DATA = [
  {
    id: 'general',
    title: 'General Documentation',
    icon: 'book',
    description: 'Release notes, licensing, and project information for X11R7.7',
    items: [
      { title: 'Release Notes for X11R7.7', href: 'xorg-docs/ReleaseNotes', formats: ['html','pdf','txt'], tags: ['release','overview'] },
      { title: 'README for X11R7.7', href: 'xorg-docs/README', formats: ['html','pdf','txt'], tags: ['readme','overview'] },
      { title: 'Licenses for X11R7.7', href: 'xorg-docs/License', formats: ['html','pdf','txt'], tags: ['license','legal'] },
      { title: 'X.Org and XFree86 Version Numbering Schemes', href: 'xorg-docs/Versions', formats: ['html','pdf','txt'], tags: ['versioning'] },
    ]
  },
  {
    id: 'config',
    title: 'Configuration & Input',
    icon: 'sliders',
    description: 'Font configuration, graphics, keyboard layout, and input method documentation',
    items: [
      { title: 'Fonts in X11R7.7', href: 'xorg-docs/fonts/fonts', formats: ['html','pdf','txt'], tags: ['fonts','configuration'] },
      { title: 'X and DPS (Display PostScript)', href: 'xorg-docs/graphics/dps', formats: ['html','pdf','txt'], tags: ['graphics','postscript'] },
      { title: 'The XKB Configuration Guide', href: 'xorg-docs/input/XKB-Config', formats: ['html','pdf','txt'], tags: ['keyboard','xkb','input','configuration'] },
      { title: 'How to Further Enhance XKB Configuration', href: 'xorg-docs/input/XKB-Enhancing', formats: ['html','pdf','txt'], tags: ['keyboard','xkb','input','advanced'] },
      { title: 'Xlib Compose Key Sequence Charts', href: 'libX11/i18n/compose/libX11-keys', formats: ['html'], tags: ['keyboard','compose','i18n'] },
    ]
  },
  {
    id: 'platforms',
    title: 'Platform-Specific',
    icon: 'monitor',
    description: 'Platform-specific documentation for Darwin/macOS and Solaris',
    items: [
      { title: 'X.Org X on Darwin and Mac OS X', href: 'xorg-docs/platforms/Darwin', formats: ['html','pdf','txt'], tags: ['macos','darwin','platform'] },
      { title: 'Information for Solaris and OpenSolaris', href: 'xorg-docs/platforms/Solaris', formats: ['html','pdf','txt'], tags: ['solaris','platform'] },
    ]
  },
  {
    id: 'devices',
    title: 'Device-Specific',
    icon: 'cpu',
    description: 'Hardware-specific documentation for various graphics chipsets',
    items: [
      { title: 'Information for ATI Mach64 Users', href: 'ati', formats: ['txt'], tags: ['ati','gpu','driver'] },
      { title: 'Information for DEC 21030 (TGA) Users', href: 'DECtga', formats: ['txt'], tags: ['dec','tga','gpu','driver'] },
      { title: 'Information for Number Nine I128 Users', href: 'I128', formats: ['txt'], tags: ['i128','gpu','driver'] },
      { title: 'Information for Intel Users', href: 'intel', formats: ['txt'], tags: ['intel','gpu','driver'] },
      { title: 'Information for Newport Users', href: 'newport', formats: ['txt'], tags: ['newport','gpu','driver'] },
      { title: 'Information for ATI Rage 128 Users', href: 'r128', formats: ['txt'], tags: ['ati','rage128','gpu','driver'] },
      { title: 'Information for SiS and XGI Users', href: 'SiS', formats: ['txt'], tags: ['sis','xgi','gpu','driver'] },
    ]
  },
  {
    id: 'man1',
    title: 'Commands',
    icon: 'terminal',
    description: 'User commands — X server, display tools, input utilities, font tools, and more',
    items: [
      { title: 'bdftopcf — convert X font from BDF to PCF', href: 'man/man1/bdftopcf.1.xhtml', formats: ['xhtml'], tags: ['font','conversion'] },
      { title: 'bdftruncate — generate truncated BDF font from ISO 10646-1', href: 'man/man1/bdftruncate.1.xhtml', formats: ['xhtml'], tags: ['font'] },
      { title: 'ccmakedep — create dependencies in makefiles using C compiler', href: 'man/man1/ccmakedep.1.xhtml', formats: ['xhtml'], tags: ['build','makefile'] },
      { title: 'cleanlinks — remove dangling symbolic links', href: 'man/man1/cleanlinks.1.xhtml', formats: ['xhtml'], tags: ['utility'] },
      { title: 'cvt — calculate VESA CVT mode lines', href: 'man/man1/cvt.1.xhtml', formats: ['xhtml'], tags: ['display','vesa'] },
      { title: 'cxpm — check an XPM file', href: 'man/man1/cxpm.1.xhtml', formats: ['xhtml'], tags: ['xpm','image'] },
      { title: 'dmxtodmx — DMX configuration file parser', href: 'man/man1/dmxtodmx.1.xhtml', formats: ['xhtml'], tags: ['dmx'] },
      { title: 'gccmakedep — create dependencies using gcc -M', href: 'man/man1/gccmakedep.1.xhtml', formats: ['xhtml'], tags: ['build','gcc'] },
      { title: 'gtf — calculate VESA GTF mode lines', href: 'man/man1/gtf.1.xhtml', formats: ['xhtml'], tags: ['display','vesa'] },
      { title: 'iceauth — ICE authority file utility', href: 'man/man1/iceauth.1.xhtml', formats: ['xhtml'], tags: ['auth','ice'] },
      { title: 'imake — C preprocessor interface to make', href: 'man/man1/imake.1.xhtml', formats: ['xhtml'], tags: ['build'] },
      { title: 'lndir — create shadow directory of symbolic links', href: 'man/man1/lndir.1.xhtml', formats: ['xhtml'], tags: ['utility','filesystem'] },
      { title: 'luit — locale and ISO 2022 support for Unicode terminals', href: 'man/man1/luit.1.xhtml', formats: ['xhtml'], tags: ['locale','unicode','terminal'] },
      { title: 'makedepend — create dependencies in makefiles', href: 'man/man1/makedepend.1.xhtml', formats: ['xhtml'], tags: ['build','makefile'] },
      { title: 'makeg — make a debuggable executable', href: 'man/man1/makeg.1.xhtml', formats: ['xhtml'], tags: ['build','debug'] },
      { title: 'mergelib — merge one library into another', href: 'man/man1/mergelib.1.xhtml', formats: ['xhtml'], tags: ['build','library'] },
      { title: 'mkdirhier — make a directory hierarchy', href: 'man/man1/mkdirhier.1.xhtml', formats: ['xhtml'], tags: ['utility','filesystem'] },
      { title: 'mkfontdir — create index of X font files', href: 'man/man1/mkfontdir.1.xhtml', formats: ['xhtml'], tags: ['font'] },
      { title: 'mkfontscale — create index of scalable font files', href: 'man/man1/mkfontscale.1.xhtml', formats: ['xhtml'], tags: ['font'] },
      { title: 'mkhtmlindex — generate index for HTML man pages', href: 'man/man1/mkhtmlindex.1.xhtml', formats: ['xhtml'], tags: ['utility','html'] },
      { title: 'revpath — generate relative path', href: 'man/man1/revpath.1.xhtml', formats: ['xhtml'], tags: ['utility'] },
      { title: 'sessreg — manage utmp/wtmp entries', href: 'man/man1/sessreg.1.xhtml', formats: ['xhtml'], tags: ['session','auth'] },
      { title: 'setxkbmap — set keyboard using XKB Extension', href: 'man/man1/setxkbmap.1.xhtml', formats: ['xhtml'], tags: ['keyboard','xkb','input'] },
      { title: 'showfont — font dumper for X font server', href: 'man/man1/showfont.1.xhtml', formats: ['xhtml'], tags: ['font'] },
      { title: 'smproxy — Session Manager Proxy', href: 'man/man1/smproxy.1.xhtml', formats: ['xhtml'], tags: ['session'] },
      { title: 'sxpm — show an XPM file', href: 'man/man1/sxpm.1.xhtml', formats: ['xhtml'], tags: ['xpm','image'] },
      { title: 'ucs2any — generate BDF fonts from ISO 10646-1', href: 'man/man1/ucs2any.1.xhtml', formats: ['xhtml'], tags: ['font','unicode'] },
      { title: 'vdltodmx — DMX configuration file parser', href: 'man/man1/vdltodmx.1.xhtml', formats: ['xhtml'], tags: ['dmx'] },
      { title: 'vmmouse_detect — VMware mouse autodetection', href: 'man/man1/vmmouse_detect.1.xhtml', formats: ['xhtml'], tags: ['vmware','mouse'] },
      { title: 'x11perf — X11 server performance test', href: 'man/man1/x11perf.1.xhtml', formats: ['xhtml'], tags: ['benchmark','performance'] },
      { title: 'x11perfcomp — X11 server performance comparison', href: 'man/man1/x11perfcomp.1.xhtml', formats: ['xhtml'], tags: ['benchmark','performance'] },
      { title: 'xauth — X authority file utility', href: 'man/man1/xauth.1.xhtml', formats: ['xhtml'], tags: ['auth','security'] },
      { title: 'xbacklight — adjust backlight brightness', href: 'man/man1/xbacklight.1.xhtml', formats: ['xhtml'], tags: ['display','backlight','randr'] },
      { title: 'xcmsdb — Device Color Characterization utility', href: 'man/man1/xcmsdb.1.xhtml', formats: ['xhtml'], tags: ['color'] },
      { title: 'xcursorgen — create X cursor from PNG images', href: 'man/man1/xcursorgen.1.xhtml', formats: ['xhtml'], tags: ['cursor','image'] },
      { title: 'Xdmx — Distributed Multi-head X server', href: 'man/man1/Xdmx.1.xhtml', formats: ['xhtml'], tags: ['server','dmx','multihead'] },
      { title: 'xdmxconfig — graphical DMX configuration tool', href: 'man/man1/xdmxconfig.1.xhtml', formats: ['xhtml'], tags: ['dmx','configuration'] },
      { title: 'xdpyinfo — display information utility', href: 'man/man1/xdpyinfo.1.xhtml', formats: ['xhtml'], tags: ['display','info'] },
      { title: 'xdriinfo — query DRI driver configuration', href: 'man/man1/xdriinfo.1.xhtml', formats: ['xhtml'], tags: ['dri','driver'] },
      { title: 'xev — print contents of X events', href: 'man/man1/xev.1.xhtml', formats: ['xhtml'], tags: ['events','debug'] },
      { title: 'xgamma — alter monitor gamma correction', href: 'man/man1/xgamma.1.xhtml', formats: ['xhtml'], tags: ['display','gamma','color'] },
      { title: 'xhost — server access control program', href: 'man/man1/xhost.1.xhtml', formats: ['xhtml'], tags: ['security','access'] },
      { title: 'xinput — configure and test X input devices', href: 'man/man1/xinput.1.xhtml', formats: ['xhtml'], tags: ['input','device'] },
      { title: 'xkbbell — XKB extension bell utility', href: 'man/man1/xkbbell.1.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard'] },
      { title: 'xkbcomp — compile XKB keyboard description', href: 'man/man1/xkbcomp.1.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard','compiler'] },
      { title: 'xkbevd — XKB event daemon', href: 'man/man1/xkbevd.1.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard','daemon'] },
      { title: 'xkbvleds — XKB virtual LEDs utility', href: 'man/man1/xkbvleds.1.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard'] },
      { title: 'xkbwatch — XKB extension watch utility', href: 'man/man1/xkbwatch.1.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard'] },
      { title: 'xkill — kill a client by its X resource', href: 'man/man1/xkill.1.xhtml', formats: ['xhtml'], tags: ['utility','window'] },
      { title: 'xlsatoms — list interned atoms on server', href: 'man/man1/xlsatoms.1.xhtml', formats: ['xhtml'], tags: ['debug','atoms'] },
      { title: 'xlsclients — list client applications on display', href: 'man/man1/xlsclients.1.xhtml', formats: ['xhtml'], tags: ['debug','clients'] },
      { title: 'Xmark — summarize x11perf results', href: 'man/man1/Xmark.1.xhtml', formats: ['xhtml'], tags: ['benchmark','performance'] },
      { title: 'xmkmf — create Makefile from Imakefile', href: 'man/man1/xmkmf.1.xhtml', formats: ['xhtml'], tags: ['build'] },
      { title: 'xmodmap — modify keymaps and pointer button mappings', href: 'man/man1/xmodmap.1.xhtml', formats: ['xhtml'], tags: ['keyboard','input','keymap'] },
      { title: 'Xnest — a nested X server', href: 'man/man1/Xnest.1.xhtml', formats: ['xhtml'], tags: ['server','nested'] },
      { title: 'Xorg — X11R7 X server', href: 'man/man1/Xorg.1.xhtml', formats: ['xhtml'], tags: ['server','xorg','core'] },
      { title: 'xprop — property displayer for X', href: 'man/man1/xprop.1.xhtml', formats: ['xhtml'], tags: ['debug','properties','window'] },
      { title: 'xrandr — RandR extension CLI', href: 'man/man1/xrandr.1.xhtml', formats: ['xhtml'], tags: ['display','randr','resolution','multihead'] },
      { title: 'xrdb — X server resource database utility', href: 'man/man1/xrdb.1.xhtml', formats: ['xhtml'], tags: ['resources','configuration'] },
      { title: 'xrefresh — refresh all or part of an X screen', href: 'man/man1/xrefresh.1.xhtml', formats: ['xhtml'], tags: ['display','refresh'] },
      { title: 'Xserver — X Window System display server', href: 'man/man1/Xserver.1.xhtml', formats: ['xhtml'], tags: ['server','core'] },
      { title: 'xset — user preference utility for X', href: 'man/man1/xset.1.xhtml', formats: ['xhtml'], tags: ['configuration','preferences'] },
      { title: 'xsetroot — root window parameter setting utility', href: 'man/man1/xsetroot.1.xhtml', formats: ['xhtml'], tags: ['display','root','background'] },
      { title: 'Xvfb — virtual framebuffer X server', href: 'man/man1/Xvfb.1.xhtml', formats: ['xhtml'], tags: ['server','virtual','framebuffer'] },
      { title: 'xvinfo — X-Video extension adaptor information', href: 'man/man1/xvinfo.1.xhtml', formats: ['xhtml'], tags: ['video','xv'] },
      { title: 'xwd — dump an image of an X window', href: 'man/man1/xwd.1.xhtml', formats: ['xhtml'], tags: ['screenshot','image'] },
      { title: 'xwininfo — window information utility', href: 'man/man1/xwininfo.1.xhtml', formats: ['xhtml'], tags: ['debug','window','info'] },
      { title: 'xwud — image displayer for X', href: 'man/man1/xwud.1.xhtml', formats: ['xhtml'], tags: ['image','display'] },
    ]
  },
  {
    id: 'man4',
    title: 'Drivers',
    icon: 'hard-drive',
    description: 'Video and input device driver documentation',
    items: [
      { title: 'ati — ATI video driver', href: 'man/man4/ati.4.xhtml', formats: ['xhtml'], tags: ['driver','ati','gpu'] },
      { title: 'cirrus — Cirrus Logic video driver', href: 'man/man4/cirrus.4.xhtml', formats: ['xhtml'], tags: ['driver','cirrus','gpu'] },
      { title: 'exa — new 2D acceleration architecture', href: 'man/man4/exa.4.xhtml', formats: ['xhtml'], tags: ['driver','acceleration','2d'] },
      { title: 'fbdev — framebuffer device video driver', href: 'man/man4/fbdev.4.xhtml', formats: ['xhtml'], tags: ['driver','framebuffer'] },
      { title: 'fbdevhw — framebuffer device access submodule', href: 'man/man4/fbdevhw.4.xhtml', formats: ['xhtml'], tags: ['driver','framebuffer'] },
      { title: 'glint — GLINT/Permedia video driver', href: 'man/man4/glint.4.xhtml', formats: ['xhtml'], tags: ['driver','glint','gpu'] },
      { title: 'i128 — Number 9 I128 video driver', href: 'man/man4/i128.4.xhtml', formats: ['xhtml'], tags: ['driver','i128','gpu'] },
      { title: 'intel — Intel integrated graphics', href: 'man/man4/intel.4.xhtml', formats: ['xhtml'], tags: ['driver','intel','gpu'] },
      { title: 'joystick — Joystick input driver', href: 'man/man4/joystick.4.xhtml', formats: ['xhtml'], tags: ['driver','input','joystick'] },
      { title: 'kbd — Keyboard input driver', href: 'man/man4/kbd.4.xhtml', formats: ['xhtml'], tags: ['driver','input','keyboard'] },
      { title: 'mga — Matrox video driver', href: 'man/man4/mga.4.xhtml', formats: ['xhtml'], tags: ['driver','matrox','gpu'] },
      { title: 'mouse — Xorg mouse input driver', href: 'man/man4/mousedrv.4.xhtml', formats: ['xhtml'], tags: ['driver','input','mouse'] },
      { title: 'neomagic — Neomagic video driver', href: 'man/man4/neomagic.4.xhtml', formats: ['xhtml'], tags: ['driver','neomagic','gpu'] },
      { title: 'newport — Newport video driver', href: 'man/man4/newport.4.xhtml', formats: ['xhtml'], tags: ['driver','newport','gpu'] },
      { title: 'nv — NVIDIA video driver', href: 'man/man4/nv.4.xhtml', formats: ['xhtml'], tags: ['driver','nvidia','gpu'] },
      { title: 'r128 — ATI Rage 128 video driver', href: 'man/man4/r128.4.xhtml', formats: ['xhtml'], tags: ['driver','ati','gpu'] },
      { title: 'radeon — ATI RADEON video driver', href: 'man/man4/radeon.4.xhtml', formats: ['xhtml'], tags: ['driver','ati','radeon','gpu'] },
      { title: 'savage — S3 Savage video driver', href: 'man/man4/savage.4.xhtml', formats: ['xhtml'], tags: ['driver','s3','gpu'] },
      { title: 'siliconmotion — Silicon Motion video driver', href: 'man/man4/siliconmotion.4.xhtml', formats: ['xhtml'], tags: ['driver','gpu'] },
      { title: 'sis — SiS and XGI video driver', href: 'man/man4/sis.4.xhtml', formats: ['xhtml'], tags: ['driver','sis','gpu'] },
      { title: 'sunffb — SUNFFB video driver', href: 'man/man4/sunffb.4.xhtml', formats: ['xhtml'], tags: ['driver','sun','gpu'] },
      { title: 'tdfx — 3Dfx video driver', href: 'man/man4/tdfx.4.xhtml', formats: ['xhtml'], tags: ['driver','3dfx','gpu'] },
      { title: 'trident — Trident video driver', href: 'man/man4/trident.4.xhtml', formats: ['xhtml'], tags: ['driver','trident','gpu'] },
      { title: 'v4l — video4linux driver', href: 'man/man4/v4l.4.xhtml', formats: ['xhtml'], tags: ['driver','video','v4l'] },
      { title: 'vesa — Generic VESA video driver', href: 'man/man4/vesa.4.xhtml', formats: ['xhtml'], tags: ['driver','vesa','gpu'] },
      { title: 'vmmouse — VMware Mouse input driver', href: 'man/man4/vmmouse.4.xhtml', formats: ['xhtml'], tags: ['driver','vmware','mouse'] },
      { title: 'vmware — VMware SVGA video driver', href: 'man/man4/vmware.4.xhtml', formats: ['xhtml'], tags: ['driver','vmware','gpu'] },
      { title: 'void — null input driver', href: 'man/man4/void.4.xhtml', formats: ['xhtml'], tags: ['driver','input'] },
      { title: 'voodoo — Voodoo video driver', href: 'man/man4/voodoo.4.xhtml', formats: ['xhtml'], tags: ['driver','voodoo','gpu'] },
    ]
  },
  {
    id: 'man5',
    title: 'Files',
    icon: 'file-text',
    description: 'Configuration file formats',
    items: [
      { title: 'Compose — X client mappings for multi-key input sequences', href: 'man/man5/Compose.5.xhtml', formats: ['xhtml'], tags: ['compose','input','configuration'] },
      { title: 'xorg.conf — configuration files for Xorg X server', href: 'man/man5/xorg.conf.5.xhtml', formats: ['xhtml'], tags: ['xorg','configuration','server'] },
    ]
  },
  {
    id: 'man7',
    title: 'Miscellaneous',
    icon: 'info',
    description: 'Overview, standards, security, and organizational information',
    items: [
      { title: 'X — a portable, network-transparent window system', href: 'man/man7/X.7.xhtml', formats: ['xhtml'], tags: ['overview','introduction'] },
      { title: 'XConsortium — X Consortium information', href: 'man/man7/Consortium.7.xhtml', formats: ['xhtml'], tags: ['organization','history'] },
      { title: 'XStandards — X Window System Standards and Specifications', href: 'man/man7/Standards.7.xhtml', formats: ['xhtml'], tags: ['standards'] },
      { title: 'xkeyboard-config — XKB data description files', href: 'man/man7/xkeyboard-config.7.xhtml', formats: ['xhtml'], tags: ['xkb','keyboard','configuration'] },
      { title: 'XOrgFoundation — X.Org Foundation information', href: 'man/man7/XOrgFoundation.7.xhtml', formats: ['xhtml'], tags: ['organization'] },
      { title: 'XProjectTeam — X.Org Group information', href: 'man/man7/XProjectTeam.7.xhtml', formats: ['xhtml'], tags: ['organization'] },
      { title: 'Xsecurity — X display access control', href: 'man/man7/Xsecurity.7.xhtml', formats: ['xhtml'], tags: ['security','access'] },
    ]
  },
  {
    id: 'client-libs',
    title: 'Developer: Client-Side Libraries',
    icon: 'code',
    description: 'API documentation for X client libraries — Xlib, XCB, extensions, toolkits',
    items: [
      { title: 'Basic Graphics Programming With The XCB Library', href: 'libxcb/tutorial/index.html', formats: ['html'], tags: ['xcb','tutorial','programming'] },
      { title: 'Xlib — C Language X Interface', href: 'libX11/libX11/libX11', formats: ['html','pdf','txt'], tags: ['xlib','api','core','programming'] },
      { title: 'Xlib Locale Framework', href: 'libX11/i18n/framework/framework', formats: ['html','pdf','txt'], tags: ['xlib','locale','i18n'] },
      { title: 'Xlib Locale Database Definition', href: 'libX11/i18n/localedb/localedb', formats: ['html','pdf','txt'], tags: ['xlib','locale','i18n','database'] },
      { title: 'X Keyboard Extension: Library Specification', href: 'libX11/XKB/xkblib', formats: ['html','pdf','txt'], tags: ['xkb','keyboard','library'] },
      { title: 'DPMS Extension Library, Version 1.0', href: 'libXext/dpmslib', formats: ['html','pdf','txt'], tags: ['dpms','power','extension'] },
      { title: 'Double Buffer Extension Library, Version 1.0', href: 'libXext/dbelib', formats: ['html','pdf','txt'], tags: ['double-buffer','extension'] },
      { title: 'X Nonrectangular Window Shape Extension Library, Version 1.0', href: 'libXext/shapelib', formats: ['html','pdf','txt'], tags: ['shape','extension','window'] },
      { title: 'X Synchronization Extension Library, Version 3.0', href: 'libXext/synclib', formats: ['html','pdf','txt'], tags: ['sync','extension'] },
      { title: 'Record Extension Library, Version 1.13', href: 'libXtst/recordlib', formats: ['html','pdf','txt'], tags: ['record','extension'] },
      { title: 'XTEST Extension Library, Version 2.2', href: 'libXtst/xtestlib', formats: ['html','pdf','txt'], tags: ['xtest','testing','extension'] },
      { title: 'X Input Device Extension Library, Version 1.0', href: 'libXi/inputlib', formats: ['html','pdf','txt'], tags: ['input','device','extension'] },
      { title: 'The Xrender Library, Version 0.7', href: 'libXrender/libXrender', formats: ['txt'], tags: ['render','extension'] },
      { title: 'X-Video Motion Compensation API, Version 1.0', href: 'libXvMC/XvMC_API', formats: ['txt'], tags: ['video','xvmc','extension'] },
      { title: 'Inter-Client Exchange Library', href: 'libICE/ICElib', formats: ['html','pdf','txt'], tags: ['ice','ipc'] },
      { title: 'X Session Management Library', href: 'libSM/SMlib', formats: ['html','pdf','txt'], tags: ['session','management'] },
      { title: 'X Toolkit Intrinsics — C Language Interface', href: 'libXt/intrinsics', formats: ['html','pdf','txt'], tags: ['toolkit','xt','widgets'] },
      { title: 'Athena Widget Set — C Language Interface', href: 'libXaw/libXaw', formats: ['html','pdf','txt'], tags: ['athena','xaw','widgets','toolkit'] },
      { title: 'Xmu and Xmuu Library API Reference', href: 'libXmu/Xmu', formats: ['html','pdf','txt'], tags: ['xmu','utility','library'] },
      { title: 'Inter-Client Communication Conventions Manual (ICCCM), Version 2.0', href: 'xorg-docs/icccm/icccm', formats: ['html','pdf','txt'], tags: ['icccm','conventions','ipc','window-manager'] },
    ]
  },
  {
    id: 'server-dev',
    title: 'Developer: Server-Side',
    icon: 'server',
    description: 'X server internals, porting layer, DDX design, and font library documentation',
    items: [
      { title: 'Xserver Provider for DTrace', href: 'xorg-server/Xserver-DTrace', formats: ['html','pdf','txt'], tags: ['dtrace','tracing','debug','server'] },
      { title: 'Definition of the Porting Layer for the X v11 Sample Server', href: 'xorg-server/Xserver-spec', formats: ['html','pdf','txt'], tags: ['porting','server','specification'] },
      { title: 'XFree86 DDX Design (Xorg server 1.12.1)', href: 'xorg-server/ddxDesign', formats: ['html','pdf','txt'], tags: ['ddx','design','server','architecture'] },
      { title: 'X Input Extension Porting', href: 'xorg-server/Xinput', formats: ['html','pdf','txt'], tags: ['input','porting','extension'] },
      { title: 'The X Font Library', href: 'libXfont/fontlib', formats: ['html','pdf','txt'], tags: ['font','library','server'] },
      { title: 'X Access Control Extension Specification', href: 'xorg-docs/Xserver/XACE-Spec', formats: ['html','pdf','txt'], tags: ['xace','access','security','server'] },
      { title: 'X Transport Interface', href: 'xtrans/xtrans', formats: ['html','pdf','txt'], tags: ['transport','network','server'] },
    ]
  },
  {
    id: 'proto-x11',
    title: 'Protocol: X11 Core & Extensions',
    icon: 'layers',
    description: 'X11 core protocol and extension protocol specifications',
    items: [
      { title: 'X Window System Protocol, Version 11, Release 6.8', href: 'xproto/x11protocol', formats: ['html','pdf','txt'], tags: ['core','protocol','specification'] },
      { title: 'Big Requests Extension, Version 2.0', href: 'bigreqsproto/bigreq', formats: ['html','pdf','txt'], tags: ['extension','protocol'] },
      { title: 'Composite Extension, Version 0.4', href: 'compositeproto/compositeproto', formats: ['txt'], tags: ['composite','extension','protocol'] },
      { title: 'DAMAGE Extension Protocol, Version 1.1', href: 'damageproto/damageproto', formats: ['txt'], tags: ['damage','extension','protocol'] },
      { title: 'DPMS Extension, Version 1.0', href: 'xextproto/dpms', formats: ['html','pdf','txt'], tags: ['dpms','power','protocol'] },
      { title: 'Double Buffer Extension Protocol', href: 'xextproto/dbe', formats: ['html','pdf','txt'], tags: ['double-buffer','protocol'] },
      { title: 'Extended Visual Information Extension', href: 'xextproto/evi', formats: ['html','pdf','txt'], tags: ['visual','protocol'] },
      { title: 'DRI2 Extension, Version 2.0', href: 'dri2proto/dri2proto', formats: ['txt'], tags: ['dri2','direct-rendering','protocol'] },
      { title: 'X Generic Event Extension', href: 'xextproto/geproto', formats: ['html','pdf','txt'], tags: ['generic-event','protocol'] },
      { title: 'XFIXES Extension, Version 5.0', href: 'fixesproto/fixesproto', formats: ['txt'], tags: ['xfixes','protocol'] },
      { title: 'X Input Extension, Version 1.5', href: 'inputproto/XIproto', formats: ['txt'], tags: ['input','protocol'] },
      { title: 'X Input Extension, Version 2.x', href: 'inputproto/XI2proto', formats: ['txt'], tags: ['input','xi2','protocol'] },
      { title: 'X Keyboard Extension', href: 'kbproto/xkbproto', formats: ['html','pdf','txt'], tags: ['xkb','keyboard','protocol'] },
      { title: 'MIT-SHM — Shared Memory Extension', href: 'xextproto/shm', formats: ['html','pdf','txt'], tags: ['shm','shared-memory','protocol'] },
      { title: 'RandR — X Resize, Rotate and Reflect Extension, Version 1.4', href: 'randrproto/randrproto', formats: ['txt'], tags: ['randr','display','protocol'] },
      { title: 'Record Extension Protocol Specification, Version 1.13', href: 'recordproto/record', formats: ['html','pdf','txt'], tags: ['record','protocol'] },
      { title: 'X Rendering Extension, Version 0.11', href: 'renderproto/renderproto', formats: ['txt'], tags: ['render','protocol'] },
      { title: 'X Resource Extension, Version 1.2', href: 'resourceproto/resproto', formats: ['txt'], tags: ['resource','protocol'] },
      { title: 'Security Extension Specification', href: 'xextproto/security', formats: ['html','pdf','txt'], tags: ['security','protocol'] },
      { title: 'X Nonrectangular Window Shape Extension Protocol, Version 1.1', href: 'xextproto/shape', formats: ['html','pdf','txt'], tags: ['shape','window','protocol'] },
      { title: 'X11 Screen Saver Extension, Version 1.0', href: 'scrnsaverproto/saver', formats: ['html','pdf','txt'], tags: ['screensaver','protocol'] },
      { title: 'X Synchronization Extension Protocol, Version 3.1', href: 'xextproto/sync', formats: ['html','pdf','txt'], tags: ['sync','protocol'] },
      { title: 'XC-MISC Extension', href: 'xcmiscproto/xc-misc', formats: ['html','pdf','txt'], tags: ['xc-misc','protocol'] },
      { title: 'XTEST Extension Protocol, Version 2.2', href: 'xextproto/xtest', formats: ['html','pdf','txt'], tags: ['xtest','testing','protocol'] },
      { title: 'X Video Extension Protocol, Version 2', href: 'videoproto/xv-protocol-v2', formats: ['txt'], tags: ['video','xv','protocol'] },
    ]
  },
  {
    id: 'proto-other',
    title: 'Protocol: Other Protocols & Specifications',
    icon: 'share-2',
    description: 'XDMCP, font service, input method, session management, ICE, and encoding specifications',
    items: [
      { title: 'X Display Manager Control Protocol (XDMCP), Version 1.1', href: 'libXdmcp/xdmcp', formats: ['html','pdf','txt'], tags: ['xdmcp','display-manager','protocol'] },
      { title: 'X Font Service Protocol, Version 2.0', href: 'fontsproto/fsproto', formats: ['html','pdf','txt'], tags: ['font','service','protocol'] },
      { title: 'X Input Method Protocol', href: 'libX11/XIM/xim', formats: ['html','pdf','txt'], tags: ['input-method','xim','i18n','protocol'] },
      { title: 'X Session Management Protocol', href: 'libSM/xsmp', formats: ['html','pdf','txt'], tags: ['session','management','protocol'] },
      { title: 'Inter-Client Exchange (ICE) Protocol', href: 'libICE/ice', formats: ['html','pdf','txt'], tags: ['ice','ipc','protocol'] },
      { title: 'Compound Text Encoding, Version 1.1', href: 'xorg-docs/ctext/ctext', formats: ['html','pdf','txt'], tags: ['encoding','text','i18n'] },
      { title: 'X Logical Font Description Conventions (XLFD), Version 1.5', href: 'xorg-docs/xlfd/xlfd', formats: ['html','pdf','txt'], tags: ['font','xlfd','naming'] },
    ]
  },
];
